version: '3.8'

services:
  nightscout-pixoo:
    container_name: nightscout-pixoo
    image: princes25/nightscout-pixoo:latest
    restart: on-failure:5
    environment:
      - NIGHTSCOUT_URL=${NIGHTSCOUT_URL}
      - PIXOO_HOST=${PIXOO_HOST}
    