version: '3.8'

services:
  nightscout-pixoo:
    container_name: nightscout-pixoo
    build: .
    environment:
      NIGHTSCOUT_URL=${NIGHTSCOUT_URL}
      PIXOO_HOST=${PIXOO_HOST}
      PIXOO_SCREEN_SIZE=64
      SCREEN_TIME=30
      RETRY_DELAY=30
    restart: unless-stopped