version: '3.8'

services:
  nightscout-pixoo:
    container_name: nightscout-pixoo
    image: princes25/nightscout-pixoo:latest
    restart: on-failure:5
    environment:
      # Required
      - NIGHTSCOUT_URL=https://your-nightscout.herokuapp.com # Change this to your Nightscout instance
      - PIXOO_HOST=192.168.1.1 # Change this to your Pixoo's IP
      # See more: https://github.com/Prince25/Nightscout-Pixoo#environment-variables
    